#!/bin/bash
#SBATCH -JSlurmPythonExample             # Job name
#SBATCH -N4 --ntasks-per-node=24          # Number of nodes and cores per node required
#SBATCH --mem-per-cpu=32G                 # Memory per core
#SBATCH -t2:00:00                             # Duration of the job (Ex: 15 mins)
#SBATCH -o Report-%j.out -e Report-err%j.err                  # Combined output and error messages file
cd $SLURM_SUBMIT_DIR                     # Change to working directory

module purge
module load gcc
module load mvapich2
module load intel-oneapi-mkl/2023.1.0
echo $PWD

srun <fullpath/>sparc -name <filename>
